language: java
install: true

jdk:
  - oraclejdk8

script:
  - $HOME/Json2Excel/.gradlew build --scan -s
  
before_cache:
  - rm -f  $HOME/Json2Excel/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/Json2Excel/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/Json2Excel/.gradle/caches/
    - $HOME/Json2Excel/.gradle/wrapper/
